version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment:
          POSTGRES_DB: pg_service_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432
        volumes:
          - ./postgresql/schemas:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    service_template-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/service_template/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/service_template:rw
        ports:
          - 8080:8080
        working_dir: /service_template
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
